import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

/**
 * Guards `src-tauri/capabilities/default.json` against the plugins' *generated*
 * ACL manifest.
 *
 * This exists because a missing grant fails **silently at runtime**: the SQL
 * plugin's `sql:default` set grants only load/select/close, so before
 * `sql:allow-execute` was added, every write — including the opening
 * `PRAGMA foreign_keys = ON` — was denied at the capability layer and the app
 * quietly degraded to localStorage (ADR-031). A unit test can't invoke Tauri,
 * but it can assert that every command our desktop adapters call is granted.
 *
 * The ACL manifest is generated by `cargo build`, so the cross-checks skip when
 * it's absent (no Rust toolchain / clean checkout) rather than failing.
 */

const TAURI_ROOT = join(process.cwd(), 'src-tauri');
const CAPABILITIES_PATH = join(TAURI_ROOT, 'capabilities', 'default.json');
const MANIFEST_PATH = join(TAURI_ROOT, 'gen', 'schemas', 'acl-manifests.json');

interface PluginManifest {
  readonly default_permission?: { readonly identifier?: string; readonly permissions?: string[] };
  readonly permissions?: Record<string, unknown>;
}

/** Commands the TypeScript adapters invoke, and the permission each one needs. */
const REQUIRED: readonly { plugin: string; permission: string; why: string }[] = [
  { plugin: 'sql', permission: 'allow-load', why: 'desktop-sql-database.ts: Database.load' },
  { plugin: 'sql', permission: 'allow-select', why: 'TauriSqlDatabase.rawQuery' },
  { plugin: 'sql', permission: 'allow-execute', why: 'TauriSqlDatabase.rawExecute — PRAGMA, migrations, every write' },
  { plugin: 'stronghold', permission: 'allow-initialize', why: 'stronghold-secret-store-factory.ts' },
  { plugin: 'stronghold', permission: 'allow-get-store-record', why: 'StrongholdSecretStore.get' },
  { plugin: 'stronghold', permission: 'allow-save-store-record', why: 'StrongholdSecretStore.set' },
  { plugin: 'stronghold', permission: 'allow-remove-store-record', why: 'StrongholdSecretStore.delete' },
  { plugin: 'stronghold', permission: 'allow-save', why: 'StrongholdSecretStore saves the snapshot after each mutation' },
  { plugin: 'http', permission: 'allow-fetch', why: 'TauriHttpTransport.send' },
];

const readJson = <T>(path: string): T => JSON.parse(readFileSync(path, 'utf8')) as T;

const grantedIds = (): Set<string> => {
  const { permissions } = readJson<{ permissions: (string | { identifier: string })[] }>(CAPABILITIES_PATH);
  return new Set(permissions.map((p) => (typeof p === 'string' ? p : p.identifier)));
};

const manifests = (): Record<string, PluginManifest> => readJson<Record<string, PluginManifest>>(MANIFEST_PATH);
const aclGenerated = existsSync(MANIFEST_PATH);

describe('tauri capabilities', () => {
  it('grants the core defaults', () => {
    expect(grantedIds().has('core:default')).toBe(true);
  });

  it.runIf(aclGenerated)('grants every plugin command the desktop adapters invoke', () => {
    const acl = manifests();
    const have = grantedIds();

    const missing = REQUIRED.filter(({ plugin, permission }) => {
      const manifest = acl[plugin];
      if (!manifest) return false; // plugin isn't built into this shell — nothing to assert
      if (have.has(`${plugin}:${permission}`)) return false;
      // Otherwise it has to arrive via the plugin's own default set.
      return !(have.has(`${plugin}:default`) && manifest.default_permission?.permissions?.includes(permission));
    });

    expect(
      missing.map((m) => `${m.plugin}:${m.permission} — needed by ${m.why}`),
      'capabilities/default.json is missing grants; these commands would be denied at runtime',
    ).toEqual([]);
  });

  it.runIf(aclGenerated)('names only permissions the generated ACL actually defines', () => {
    const acl = manifests();
    const unknown = [...grantedIds()].filter((id) => {
      const [plugin, permission] = id.split(':');
      if (plugin === undefined || permission === undefined) return true;
      const manifest = acl[plugin];
      if (!manifest) return false; // core / not-built plugins are out of scope here
      if (permission === 'default') return manifest.default_permission === undefined;
      return !(permission in (manifest.permissions ?? {}));
    });
    expect(unknown, 'these permission identifiers do not exist in the generated ACL').toEqual([]);
  });
});
