import { describe, it, expect } from 'vitest';
import { Hg1, type Hg1Payload } from '@domain/harvest/hg1-metadata';
import { scrambleHg1Codec } from '@domain/harvest/scramble-hg1-codec';

describe('Hg1 metadata codec', () => {
  const payload: Hg1Payload = {
    v: 1,
    source: 'WorkItem',
    templateId: 'tpl-9',
  };

  it('round-trips through embed/extract and hides from the note body', () => {
    const notes = 'Investigating the login bug';
    const embedded = Hg1.embed(notes, payload);
    expect(embedded).toContain('```hg1');
    expect(Hg1.strip(embedded)).toBe(notes);
    expect(Hg1.extract(embedded)).toEqual(payload);
  });

  it('handles empty user notes', () => {
    const embedded = Hg1.embed('', payload);
    expect(Hg1.strip(embedded)).toBe('');
    expect(Hg1.extract(embedded)).toEqual(payload);
  });

  it('replaces an existing block instead of stacking', () => {
    const once = Hg1.embed('note', payload);
    const twice = Hg1.embed(once, { ...payload, source: 'Meeting' });
    expect((twice.match(/```hg1/g) ?? []).length).toBe(1);
    expect(Hg1.extract(twice)?.source).toBe('Meeting');
  });

  it('strip returns the trimmed input untouched when there is no tag', () => {
    expect(Hg1.strip('just notes  \n\n')).toBe('just notes');
    expect(Hg1.strip('  leading and trailing  ')).toBe('  leading and trailing');
  });

  it('extract returns null for plain text with no tag', () => {
    expect(Hg1.extract('just notes, nothing embedded')).toBeNull();
  });

  it('extract returns null for malformed base64 in the block', () => {
    expect(Hg1.extract('```hg1\n!!!notbase64!!!\n```')).toBeNull();
  });

  it('extract returns null for valid base64 that is not JSON', () => {
    // "not json" base64url-encoded.
    const notJsonB64 = Buffer.from('not json', 'utf-8').toString('base64url');
    expect(Hg1.extract(`\`\`\`hg1\n${notJsonB64}\n\`\`\``)).toBeNull();
  });

  it('extract returns null when the payload version is not 1', () => {
    const bad = { v: 2, source: 'Manual' };
    const b64 = Buffer.from(JSON.stringify(bad), 'utf-8').toString('base64url');
    expect(Hg1.extract(`\`\`\`hg1\n${b64}\n\`\`\``)).toBeNull();
  });

  it('survives a unicode payload', () => {
    const unicodePayload: Hg1Payload = { v: 1, source: 'Meeting', templateId: '日本語 🎉 café' };
    const embedded = Hg1.embed('notes with 日本語', unicodePayload);
    expect(Hg1.extract(embedded)).toEqual(unicodePayload);
  });

  it('only strips the trailing hg1 block, leaving other code fences intact', () => {
    const notes = 'Some notes\n\n```js\nconsole.log("keep me");\n```\n\nMore text';
    const embedded = Hg1.embed(notes, payload);
    const stripped = Hg1.strip(embedded);
    expect(stripped).toContain('```js');
    expect(stripped).toContain('console.log("keep me");');
    expect(stripped).not.toContain('```hg1');
    expect(Hg1.extract(embedded)).toEqual(payload);
  });

  it('treats a payload without templateId correctly (optional field absent)', () => {
    const noTemplate: Hg1Payload = { v: 1, source: 'Manual' };
    const embedded = Hg1.embed('note', noTemplate);
    expect(Hg1.extract(embedded)).toEqual(noTemplate);
  });

  it('matches the locked backward-compat GOLDEN vector (pre-existing plain tag)', () => {
    // Generated by encoding `{"v":1,"source":"WorkItem","templateId":"tpl-golden"}`
    // with the CURRENT (pre-pluggable) plain base64url logic — locks the format so
    // tags written by older app versions remain decodable forever.
    const GOLDEN_NOTES =
      'Fixed the thing\n\n\n```hg1\neyJ2IjoxLCJzb3VyY2UiOiJXb3JrSXRlbSIsInRlbXBsYXRlSWQiOiJ0cGwtZ29sZGVuIn0\n```';
    expect(Hg1.extract(GOLDEN_NOTES)).toEqual({
      v: 1,
      source: 'WorkItem',
      templateId: 'tpl-golden',
    });
    expect(Hg1.strip(GOLDEN_NOTES)).toBe('Fixed the thing');
  });

  it('embeds with the scrambleHg1Codec and auto-detects it on extract', () => {
    const plainEmbedded = Hg1.embed('note', payload);
    const scrambleEmbedded = Hg1.embed('note', payload, scrambleHg1Codec);

    expect(Hg1.extract(scrambleEmbedded)).toEqual(payload);

    const plainBody = /```hg1\n([\s\S]*?)\n```/.exec(plainEmbedded)![1]!.trim();
    const scrambleBody = /```hg1\n([\s\S]*?)\n```/.exec(scrambleEmbedded)![1]!.trim();
    expect(scrambleBody.startsWith('s1:')).toBe(true);
    expect(scrambleBody).not.toBe(plainBody);
  });

  it('extracts both plain and scramble bodies through the same extract call', () => {
    const plainEmbedded = Hg1.embed('a', { ...payload, source: 'Manual' });
    const scrambleEmbedded = Hg1.embed('b', { ...payload, source: 'Meeting' }, scrambleHg1Codec);

    expect(Hg1.extract(plainEmbedded)).toEqual({ ...payload, source: 'Manual' });
    expect(Hg1.extract(scrambleEmbedded)).toEqual({ ...payload, source: 'Meeting' });
  });
});
