import { describe, it, expect } from 'vitest';
import { fromBase64Url, plainHg1Codec, toBase64Url } from '@domain/harvest/plain-hg1-codec';

describe('plainHg1Codec', () => {
  it('round-trips a JSON payload', () => {
    const json = JSON.stringify({ v: 1, source: 'Manual' });
    const encoded = plainHg1Codec.encode(json);
    expect(plainHg1Codec.decode(encoded)).toBe(json);
  });

  it('round-trips unicode content', () => {
    const json = JSON.stringify({ v: 1, note: '日本語 emoji 🎉 café' });
    const encoded = plainHg1Codec.encode(json);
    expect(plainHg1Codec.decode(encoded)).toBe(json);
  });

  it('round-trips an empty string', () => {
    const encoded = plainHg1Codec.encode('');
    expect(plainHg1Codec.decode(encoded)).toBe('');
  });

  it('returns null for garbage input', () => {
    expect(plainHg1Codec.decode('!!!not-base64!!!')).toBeNull();
  });

  it('has the "plain" scheme tag', () => {
    expect(plainHg1Codec.scheme).toBe('plain');
  });

  it('matches the locked golden byte-for-byte encoding', () => {
    const payload = { v: 1, source: 'WorkItem', templateId: 'tpl-golden' };
    const json = JSON.stringify(payload);
    // Locked format: unprefixed base64url, generated by the original hg1 logic.
    const GOLDEN = 'eyJ2IjoxLCJzb3VyY2UiOiJXb3JrSXRlbSIsInRlbXBsYXRlSWQiOiJ0cGwtZ29sZGVuIn0';
    expect(toBase64Url(json)).toBe(GOLDEN);
    expect(plainHg1Codec.encode(json)).toBe(GOLDEN);
    expect(fromBase64Url(GOLDEN)).toBe(json);
    expect(plainHg1Codec.decode(GOLDEN)).toBe(json);
  });
});
